site_name: Nalej

nav:
    - Welcome to Nalej: README.md
    - Organization:
      - Organization and user management: 'organization/organization-1.md'
    - Resources:
      - Cluster monitoring: resources/resources-1.md
      - Application cluster installation: resources/appcluster_installation.md
    - Devices:
      - Adding, managing and deleting devices: devices/devices-1.md
    - Apps:
      - Deployment, management and removal: applications/applications-1.md
      - Application descriptor: applications/app_descriptors.md
      - The Application Graph: applications/appdiagram.md
    - Tutorials:
      - Initial login in Nalej: tutorials/initiallogin.md
      - Adding users in the system: tutorials/addingusers.md
      - Application deployment: tutorials/appdeployment_wclusters.md
      - Docker Compose application: tutorials/dockerappinnalej.md
      - Application with devices: tutorials/appwithdevices.md


theme:
  name: windmill
extra_css: 
  - stylesheets/extra.css
extra:
  version: 0.2.0
